version: '3.7'

services:

  frontend:
    build:
      context: .
      dockerfile: ./docker/frontend/Dockerfile
    env_file: ./.env
    ports:
      - "3000:3000"
    depends_on:
      - backend
    command: yarn run dev

  backend:
    build:
      context: .
      dockerfile: ./docker/backend/Dockerfile
    env_file: ./.env
    volumes:
      - .:/app:delegated
    ports:
      - "5000:5000"
    depends_on:
      - database
    command: uvicorn app.main:app --host 0.0.0.0 --port 5000 --reload

  database:
    image: postgres:15.3-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: biblio
    ports:
      - 5432:5432
    volumes:
    - bibliograph-pgdata:/var/lib/postgresql/data

  alembic:
    build:
      context: .
      dockerfile: ./docker/backend/Dockerfile
    env_file:
      - .env
    command: alembic upgrade head
    depends_on:
      - database

volumes:
  bibliograph-pgdata:
