FROM python:3.11-alpine

WORKDIR /app

RUN apk add --no-cache gcc \
    musl-dev \
    make \
    libffi-dev \
    openssl-dev

COPY requirements.lock ./

RUN PYTHONDONTWRITEBYTECODE=1 pip install --no-cache-dir -r requirements.lock

RUN adduser -D user && chown -R user:user ./

USER user

COPY --chown=user:user ./ ./

CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "5000", "--reload"]
