"""add index and created_at

Revision ID: 59486c32aa36
Revises: b928a930bdd2
Create Date: 2023-06-16 23:46:01.497174

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59486c32aa36'
down_revision = 'b928a930bdd2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.drop_constraint('users_username_email_key', 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_unique_constraint(None, 'users', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint('users_username_email_key', 'users', ['username', 'email'])
    op.drop_column('users', 'created_at')
    # ### end Alembic commands ###
