"""init

Revision ID: 735b99f05861
Revises: 
Create Date: 2023-06-16 01:17:56.444972

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '735b99f05861'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
